services:
  - type: web
    name: portfolio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUD_NAME
      - key: API_KEY
      - key: API_SECRET
